name: Deploy to GitHub Pages via angular-cli-ghpages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Find & Replace
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "___test___"
        replace: ${{ secrets.MY_TEST }}
        include: "**secrets.*.ts"
        regex: false

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 18.x
    

    - name: Prepare and deploy
      env:
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        MY_NAME: ${{ secrets.MY_NAME }}
        MY_EMAIL: ${{ secrets.MY_EMAIL }}
      run: |
        npm install
        npm run lint
        npm run ng -- deploy --branch="gh-pages" --cname=snotaro.dev --name="$MY_NAME" --email="$MY_EMAIL" --no-silent
